def scale_note_for pitch_family, modifier
  ScaleNote.where(pitch_family: pitch_family, modifier: modifier).first
end

Key.create(scale_note: scale_note_for("B", -1), mode: Mode.major)
Key.create(scale_note: scale_note_for("B", -1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("B", 0), mode: Mode.major)
Key.create(scale_note: scale_note_for("B", 0), mode: Mode.minor)
Key.create(scale_note: scale_note_for("B", 1), mode: Mode.major)
Key.create(scale_note: scale_note_for("B", 1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("C", -1), mode: Mode.major)
Key.create(scale_note: scale_note_for("C", -1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("C", 0), mode: Mode.major)
Key.create(scale_note: scale_note_for("C", 0), mode: Mode.minor)
Key.create(scale_note: scale_note_for("C", 1), mode: Mode.major)
Key.create(scale_note: scale_note_for("C", 1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("D", -1), mode: Mode.major)
Key.create(scale_note: scale_note_for("D", -1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("D", 0), mode: Mode.major)
Key.create(scale_note: scale_note_for("D", 0), mode: Mode.minor)
Key.create(scale_note: scale_note_for("D", 1), mode: Mode.major)
Key.create(scale_note: scale_note_for("D", 1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("E", -1), mode: Mode.major)
Key.create(scale_note: scale_note_for("E", -1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("E", 0), mode: Mode.major)
Key.create(scale_note: scale_note_for("E", 0), mode: Mode.minor)
Key.create(scale_note: scale_note_for("E", 1), mode: Mode.major)
Key.create(scale_note: scale_note_for("E", 1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("F", -1), mode: Mode.major)
Key.create(scale_note: scale_note_for("F", -1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("F", 0), mode: Mode.major)
Key.create(scale_note: scale_note_for("F", 0), mode: Mode.minor)
Key.create(scale_note: scale_note_for("F", 1), mode: Mode.major)
Key.create(scale_note: scale_note_for("F", 1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("G", -1), mode: Mode.major)
Key.create(scale_note: scale_note_for("G", -1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("G", 0), mode: Mode.major)
Key.create(scale_note: scale_note_for("G", 0), mode: Mode.minor)
Key.create(scale_note: scale_note_for("G", 1), mode: Mode.major)
Key.create(scale_note: scale_note_for("G", 1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("A", -1), mode: Mode.major)
Key.create(scale_note: scale_note_for("A", -1), mode: Mode.minor)
Key.create(scale_note: scale_note_for("A", 0), mode: Mode.major)
Key.create(scale_note: scale_note_for("A", 0), mode: Mode.minor)
Key.create(scale_note: scale_note_for("A", 1), mode: Mode.major)
Key.create(scale_note: scale_note_for("A", 1), mode: Mode.minor)