(0..10).each {|octal_index|
  base = octal_index * 12
  Note.create(pitch_id: base+1,  scale_note_id: ScaleNote.find_by(pitch_family: "B", modifier: 1).id)
  Note.create(pitch_id: base+1,  scale_note_id: ScaleNote.find_by(pitch_family: "C", modifier: 0).id)
  Note.create(pitch_id: base+2,  scale_note_id: ScaleNote.find_by(pitch_family: "C", modifier: 1).id)
  Note.create(pitch_id: base+2,  scale_note_id: ScaleNote.find_by(pitch_family: "D", modifier: -1).id)
  Note.create(pitch_id: base+3,  scale_note_id: ScaleNote.find_by(pitch_family: "D", modifier: 0).id)
  Note.create(pitch_id: base+4,  scale_note_id: ScaleNote.find_by(pitch_family: "D", modifier: 1).id)
  Note.create(pitch_id: base+4,  scale_note_id: ScaleNote.find_by(pitch_family: "E", modifier: -1).id)
  Note.create(pitch_id: base+5,  scale_note_id: ScaleNote.find_by(pitch_family: "E", modifier: 0).id)
  Note.create(pitch_id: base+5,  scale_note_id: ScaleNote.find_by(pitch_family: "F", modifier: -1).id)
  Note.create(pitch_id: base+6,  scale_note_id: ScaleNote.find_by(pitch_family: "E", modifier: 1).id)
  Note.create(pitch_id: base+6,  scale_note_id: ScaleNote.find_by(pitch_family: "F", modifier: 0).id)
  Note.create(pitch_id: base+7,  scale_note_id: ScaleNote.find_by(pitch_family: "F", modifier: 1).id)
  Note.create(pitch_id: base+7,  scale_note_id: ScaleNote.find_by(pitch_family: "G", modifier: -1).id)
  Note.create(pitch_id: base+8,  scale_note_id: ScaleNote.find_by(pitch_family: "G", modifier: 0).id)
  Note.create(pitch_id: base+9,  scale_note_id: ScaleNote.find_by(pitch_family: "G", modifier: 1).id)
  Note.create(pitch_id: base+9,  scale_note_id: ScaleNote.find_by(pitch_family: "A", modifier: -1).id)
  Note.create(pitch_id: base+10, scale_note_id: ScaleNote.find_by(pitch_family: "A", modifier: 0).id)
  Note.create(pitch_id: base+11, scale_note_id: ScaleNote.find_by(pitch_family: "A", modifier: 1).id)
  Note.create(pitch_id: base+11, scale_note_id: ScaleNote.find_by(pitch_family: "B", modifier: -1).id)
  Note.create(pitch_id: base+12, scale_note_id: ScaleNote.find_by(pitch_family: "B", modifier: 0).id)
  Note.create(pitch_id: base+12, scale_note_id: ScaleNote.find_by(pitch_family: "C", modifier: -1).id)
}